server:
  port: 8222
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          predicates:
            - Path=/auth/**
          uri: http://localhost:8050
        - id: coupon-generation-service
          predicates:
            - Path=/api/coupons
          uri: http://localhost:8060
        - id: search-service
          predicates:
            - Path=/api/coupons/search/**
          uri: http://localhost:8070
